name: ci-wf
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Steps
        run: echo "Welcome to CI Pipeline for this Repo" 
      - name: Checkout Repository
        uses: actions/checkout@v4  
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"           

